version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: config/app.env

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kurodev
      - MONGO_INITDB_ROOT_PASSWORD=11062001Phong.
    ports:
      - "27017:27017"