// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "hoaiphong01012002@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/accounts/create": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Create the account's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Create Account Information",
                "parameters": [
                    {
                        "description": "Account data",
                        "name": "Account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/accounts/delete": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Delete the account's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Delete Account Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/accounts/get/_id": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get the account's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Get Account Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attendance ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/accounts/get/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get the account's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Get Account Information",
                "responses": {}
            }
        },
        "/api/v1/accounts/get/name": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get the account's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Get Account Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attendance ID",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/accounts/update": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Update the account's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Update Account Information",
                "parameters": [
                    {
                        "description": "Account data",
                        "name": "Account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account_domain.Input"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Attendance ID",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/attendances/_id": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the attendance's information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Update Attendance Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attendance ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Attendance data",
                        "name": "attendance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/attendance_domain.Input"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the attendance's information by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Delete Attendance Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attendance ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/attendances/create": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Create the attendance's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Create Attendance Information",
                "parameters": [
                    {
                        "description": "Attendance data",
                        "name": "CreateOneAttendance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/attendance_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/attendances/get/_id": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the attendance's information name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Get Attendance Information By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attendance ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/attendances/get/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the attendance's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Get Attendance Information",
                "responses": {}
            }
        },
        "/api/v1/attendances/get/email": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the attendance's information name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Get Attendance Information By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attendance ID",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/benefits/_id": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the benefit's information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Benefit"
                ],
                "summary": "Update Benefit Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Benefit ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Benefit data",
                        "name": "attendance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/benefits_domain.Input"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the benefit's information by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Benefit"
                ],
                "summary": "Delete Benefit Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Benefit ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/benefits/create": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Create the benefit's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Benefit"
                ],
                "summary": "Create Benefit Information",
                "parameters": [
                    {
                        "description": "Benefit data",
                        "name": "Benefit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/benefits_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/benefits/get/_id": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the benefit's information name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Benefit"
                ],
                "summary": "Get Benefit Information By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Benefit ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/benefits/get/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the benefit's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Benefit"
                ],
                "summary": "Get Benefit Information",
                "responses": {}
            }
        },
        "/api/v1/benefits/get/email": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the benefit's information name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Benefit"
                ],
                "summary": "Get Benefit Information By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Benefit ID",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/budgets/create": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Create the budget's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budget"
                ],
                "summary": "Create Budget Information",
                "parameters": [
                    {
                        "description": "Budget data",
                        "name": "Budget",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/budgets_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/budgets/delete": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Delete the budget's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budget"
                ],
                "summary": "Delete Budget Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Budget ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/budgets/get/_id": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get by id the budget's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budget"
                ],
                "summary": "Get by id Budget Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Budget ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/budgets/get/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get the budget's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budget"
                ],
                "summary": "Get Budget Information",
                "responses": {}
            }
        },
        "/api/v1/budgets/get/name": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get by name the budget's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budget"
                ],
                "summary": "Get by name Budget Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Budget name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/budgets/update": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get by name the budget's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budget"
                ],
                "summary": "Get by name Budget Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Budget name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Budget data",
                        "name": "Budget",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/budgets_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/contracts/create": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Create the contract's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "Create Contract Information",
                "parameters": [
                    {
                        "description": "Contract data",
                        "name": "Contract",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/contracts/delete/_id": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the contract's information by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "Delete Contract Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/contracts/get/_id": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the contract's information by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "Get Contract Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/contracts/get/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the contract's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "Get Contract Information",
                "responses": {}
            }
        },
        "/api/v1/contracts/get/email": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get one the contract's information by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "Get one Contract Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/contracts/update": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Update the contract's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "Update Contract Information",
                "parameters": [
                    {
                        "description": "Contract data",
                        "name": "Contract",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts_domain.Input"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/departments/create": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Create the department's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Create Department Information",
                "parameters": [
                    {
                        "description": "Department data",
                        "name": "Department",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/departments_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/departments/delete": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the department's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Delete Department Information",
                "responses": {}
            }
        },
        "/api/v1/departments/get/_id": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the department's information name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Get Department Information By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/departments/get/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the department's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Get Department Information",
                "responses": {}
            }
        },
        "/api/v1/departments/get/name": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the department's information name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Get Department Information By Name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/departments/update": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the department's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Update Department Information",
                "responses": {}
            }
        },
        "/api/v1/employees/create": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Create the employee's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Create Employee Information",
                "parameters": [
                    {
                        "description": "Employee data",
                        "name": "attendance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/employees/delete": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the employee's information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Delete Employee Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/employees/get/_id": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the employee's information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Get Employee Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/employees/get/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the employee's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Get Employee Information",
                "responses": {}
            }
        },
        "/api/v1/employees/get/name": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the employee's information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Get Employee Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/employees/update": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Create the employee's information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Create Employee Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Employee data",
                        "name": "attendance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/leave_requests/create": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Create the leave request's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leave Request"
                ],
                "summary": "Create Leave Request Information",
                "parameters": [
                    {
                        "description": "Leave Request data",
                        "name": "LeaveRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/leave_request_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/leave_requests/delete": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Delete the leave request's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leave Request"
                ],
                "summary": "Delete Leave Request Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Leave Request ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/leave_requests/get/_id": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get one by email the leave request's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leave Request"
                ],
                "summary": "Get one by id Leave Request Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/leave_requests/get/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get all the leave request's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leave Request"
                ],
                "summary": "Get all Leave Request Information",
                "responses": {}
            }
        },
        "/api/v1/leave_requests/get/email": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get one by email the leave request's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leave Request"
                ],
                "summary": "Get one by email Leave Request Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/leave_requests/update": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the leave request's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leave Request"
                ],
                "summary": "Update Leave Request Information",
                "responses": {}
            }
        },
        "/api/v1/performance_reviews/create": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Create the performance review's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Performance Review"
                ],
                "summary": "Create Performance Review Information",
                "parameters": [
                    {
                        "description": "Performance Review data",
                        "name": "PerformanceReview",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/performance_review_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/performance_reviews/delete": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Delete the performance review's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Performance Review"
                ],
                "summary": "Delete Performance Review Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Performance Review  ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/performance_reviews/get/_id": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get the performance review's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Performance Review"
                ],
                "summary": "Get Performance Review Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Performance Review  ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/performance_reviews/get/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get all the performance review's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Performance Review"
                ],
                "summary": "Get all Performance Review Information",
                "responses": {}
            }
        },
        "/api/v1/performance_reviews/get/email": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get the performance review's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Performance Review"
                ],
                "summary": "Get Performance Review Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Performance Review  ID",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/performance_reviews/update": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Update the performance review's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Performance Review"
                ],
                "summary": "Update Performance Review Information",
                "parameters": [
                    {
                        "description": "Performance Review data",
                        "name": "PerformanceReview",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/performance_review_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/roles/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create new role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Create role",
                "parameters": [
                    {
                        "description": "Role data",
                        "name": "Role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role_domain.Input"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/roles/delete": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the role's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Delete Role Information",
                "responses": {}
            }
        },
        "/api/v1/roles/get/_id": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the role's information name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Get Role Information By Name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/roles/get/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the role's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Get Role Information",
                "responses": {}
            }
        },
        "/api/v1/roles/get/title": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the role's information name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Get Role Information By Name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "title",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/roles/update": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the role's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Update Role Information",
                "responses": {}
            }
        },
        "/api/v1/salaries/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create new salary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Salary"
                ],
                "summary": "Create salary",
                "parameters": [
                    {
                        "description": "Salary data",
                        "name": "Salary",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/salary_domain.Salary"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/salaries/delete": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the salary's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Salary"
                ],
                "summary": "Delete Salary Information",
                "responses": {}
            }
        },
        "/api/v1/salaries/get/_id": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the salary's information id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Salary"
                ],
                "summary": "Get Salary Information By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/salaries/get/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the salary's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Salary"
                ],
                "summary": "Get Salary Information",
                "responses": {}
            }
        },
        "/api/v1/salaries/get/role": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the salary's information role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Salary"
                ],
                "summary": "Get Salary Information By Role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "role",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/salaries/update": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the salary's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Salary"
                ],
                "summary": "Update Salary Information",
                "responses": {}
            }
        },
        "/api/v1/users/delete": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the user's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete User Information",
                "responses": {}
            }
        },
        "/api/v1/users/get/info": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the user's information using the access token stored in cookies.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User Information",
                "responses": {}
            }
        },
        "/api/v1/users/login": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Login user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "LoginUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_domain.SignIn"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/users/logout": {
            "get": {
                "description": "Logout the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Logout user",
                "responses": {}
            }
        }
    },
    "definitions": {
        "account_domain.Input": {
            "type": "object",
            "properties": {
                "account_name": {
                    "type": "string"
                },
                "account_number": {
                    "type": "string"
                },
                "account_type": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                }
            }
        },
        "attendance_domain.Input": {
            "type": "object",
            "properties": {
                "check_in_time": {
                    "type": "string"
                },
                "check_out_time": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "employee": {
                    "type": "string"
                },
                "status": {
                    "description": "Example values: \"Present\", \"Leave\", \"Sick\"",
                    "type": "string"
                }
            }
        },
        "benefits_domain.Input": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "benefit_type": {
                    "description": "Example: \"Health Insurance\", \"Social Insurance\", \"Meal Allowance\"",
                    "type": "string"
                },
                "employee_email": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "budgets_domain.Input": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "budget_name": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "contracts_domain.Input": {
            "type": "object",
            "properties": {
                "contract_type": {
                    "description": "Example: \"Full-Time\", \"Part-Time\", \"Temporary\"",
                    "type": "string"
                },
                "employee": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "salary": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "description": "Example: \"Active\", \"Expired\"",
                    "type": "string"
                }
            }
        },
        "departments_domain.Input": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Responsible for managing employee relations, recruitment, and company culture."
                },
                "managerEmail": {
                    "type": "string",
                    "example": "admin@admin.com"
                },
                "name": {
                    "type": "string",
                    "example": "Human Resources"
                }
            }
        },
        "employees_domain.Input": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Bình Thuận"
                },
                "avatarURL": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string",
                    "example": "01/01/2002"
                },
                "dayOfWork": {
                    "type": "string",
                    "example": "30/8/2024"
                },
                "department": {
                    "type": "string",
                    "example": "marketing"
                },
                "email": {
                    "type": "string",
                    "example": "hoaiphong01012002@gmail.com"
                },
                "firstName": {
                    "type": "string",
                    "example": "Ngô"
                },
                "gender": {
                    "type": "string",
                    "example": "Nam"
                },
                "lastName": {
                    "type": "string",
                    "example": "Hoài Phong"
                },
                "phone": {
                    "type": "string",
                    "example": "0329245971"
                },
                "role": {
                    "type": "string",
                    "example": "developer"
                }
            }
        },
        "leave_request_domain.Input": {
            "type": "object",
            "properties": {
                "employee": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "leave_type": {
                    "description": "Example: \"Sick Leave\", \"Annual Leave\", \"Unpaid Leave\"",
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "description": "Example: \"Approved\", \"Pending\", \"Rejected\"",
                    "type": "string"
                }
            }
        },
        "performance_review_domain.Input": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "string"
                },
                "performance_score": {
                    "type": "integer"
                },
                "review_date": {
                    "type": "string"
                },
                "reviewer_id": {
                    "type": "string"
                }
            }
        },
        "role_domain.Input": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "The admin role has full access and control over the system."
                },
                "title": {
                    "type": "string",
                    "example": "Admin"
                }
            }
        },
        "salary_domain.Salary": {
            "type": "object",
            "properties": {
                "base_salary": {
                    "type": "number"
                },
                "bonus": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "deductions": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "net_salary": {
                    "type": "number"
                },
                "role_id": {
                    "type": "string"
                },
                "unit_currency": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "user_domain.SignIn": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin@admin.com"
                },
                "password_hash": {
                    "type": "string",
                    "example": "12345"
                }
            }
        }
    },
    "tags": [
        {
            "description": "represents the attendance information of an employee.",
            "name": "Attendance"
        },
        {
            "description": "represents the benefits an employee receives.",
            "name": "Benefit"
        },
        {
            "description": "represents an employment contract of an employee.",
            "name": "Contract"
        },
        {
            "description": "struct represents a department within the company.",
            "name": "Department"
        },
        {
            "description": "struct represents an employee in the HR system.",
            "name": "Employee"
        },
        {
            "description": "represents a leave request by an employee.",
            "name": "Leave Request"
        },
        {
            "description": "represents performance evaluations of an employee.",
            "name": "Performance Review"
        },
        {
            "description": "struct represents a role or job role.",
            "name": "Role"
        },
        {
            "description": "represents the salary information of an employee.",
            "name": "Salary"
        },
        {
            "description": "represents a user in the system.",
            "name": "User"
        },
        {
            "description": "Stores information about financial accounts like bank accounts or cash wallets, tracking balance and account type.",
            "name": "Account"
        },
        {
            "description": "Manages financial transactions for accounts, tracking income and expenses, amounts, and transaction dates.",
            "name": "Budget"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Shop E-commerce ERP",
	Description:      "This is a server for Kuro API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
