basePath: /api/v1
definitions:
  departments_domain.Department:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  role_domain.Role:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      title:
        type: string
      updatedAt:
        type: string
    type: object
  salary_domain.Salary:
    properties:
      base_salary:
        type: number
      bonus:
        type: number
      created_at:
        type: string
      deductions:
        type: number
      id:
        type: string
      net_salary:
        type: number
      role_id:
        type: string
      unit_currency:
        type: string
      updated_at:
        type: string
    type: object
  user_domain.SignIn:
    properties:
      email:
        example: admin@admin.com
        type: string
      password:
        example: "12345"
        type: string
    type: object
  user_domain.User:
    properties:
      asset_url:
        type: string
      avatar_url:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      password_hash:
        description: Hash of the password
        type: string
      phone:
        type: string
      provider:
        type: string
      role:
        description: 'Example: "Admin", "Manager", "Employee"'
        type: string
      updated_at:
        type: string
      username:
        type: string
      verification_code:
        type: string
      verify:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: hoaiphong01012002@gmail.com
    name: API Support
  description: This is a server for Kuro API
  title: Shop E-commerce ERP
  version: "1.0"
paths:
  /api/v1/departments/create:
    post:
      consumes:
      - application/json
      description: Create the department's information
      produces:
      - application/json
      responses:
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Create Department Information
      tags:
      - Department
  /api/v1/departments/delete:
    delete:
      consumes:
      - application/json
      description: Deletes the department's information
      produces:
      - application/json
      responses:
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Delete Department Information
      tags:
      - Department
  /api/v1/departments/get/all:
    get:
      consumes:
      - application/json
      description: Retrieves the department's information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/departments_domain.Department'
            type: array
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Get Department Information
      tags:
      - Department
  /api/v1/departments/get/one/_id:
    get:
      consumes:
      - application/json
      description: Retrieves the department's information name
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/departments_domain.Department'
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Get Department Information By ID
      tags:
      - Department
  /api/v1/departments/get/one/name:
    get:
      consumes:
      - application/json
      description: Retrieves the department's information name
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/departments_domain.Department'
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Get Department Information By Name
      tags:
      - Department
  /api/v1/departments/update:
    patch:
      consumes:
      - application/json
      description: Updates the department's information
      produces:
      - application/json
      responses:
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Update Department Information
      tags:
      - Department
  /api/v1/roles/create:
    post:
      consumes:
      - application/json
      description: Create new role
      parameters:
      - description: Role data
        in: body
        name: Role
        required: true
        schema:
          $ref: '#/definitions/role_domain.Role'
      produces:
      - application/json
      responses:
        "201":
          description: 'status: success, message: created a new role'
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Create role
      tags:
      - Role
  /api/v1/roles/get/all:
    get:
      consumes:
      - application/json
      description: Retrieves the role's information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/role_domain.Role'
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Get Role Information
      tags:
      - Role
  /api/v1/roles/get/one/_id:
    get:
      consumes:
      - application/json
      description: Retrieves the role's information name
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/role_domain.Role'
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Get Role Information By Name
      tags:
      - Role
  /api/v1/roles/get/one/title:
    get:
      consumes:
      - application/json
      description: Retrieves the role's information name
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/role_domain.Role'
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Get Role Information By Name
      tags:
      - Role
  /api/v1/roles/update:
    patch:
      consumes:
      - application/json
      description: Updates the role's information
      produces:
      - application/json
      responses:
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Update Role Information
      tags:
      - Role
  /api/v1/salaries/create:
    post:
      consumes:
      - application/json
      description: Create new salary
      parameters:
      - description: Salary data
        in: body
        name: Role
        required: true
        schema:
          $ref: '#/definitions/salary_domain.Salary'
      produces:
      - application/json
      responses:
        "201":
          description: 'status: success, message: created a new role'
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Create salary
      tags:
      - Salary
  /api/v1/salaries/get/all:
    get:
      consumes:
      - application/json
      description: Retrieves the salary's information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/salary_domain.Salary'
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Get Salary Information
      tags:
      - Salary
  /api/v1/salaries/get/one/_id:
    get:
      consumes:
      - application/json
      description: Retrieves the salary's information id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/salary_domain.Salary'
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Get Salary Information By ID
      tags:
      - Salary
  /api/v1/salaries/get/one/role:
    get:
      consumes:
      - application/json
      description: Retrieves the salary's information role
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/salary_domain.Salary'
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Get Salary Information By Role
      tags:
      - Salary
  /api/v1/salaries/update:
    patch:
      consumes:
      - application/json
      description: Updates the salary's information
      produces:
      - application/json
      responses:
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Update Salary Information
      tags:
      - Salary
  /api/v1/users/get/info:
    get:
      consumes:
      - application/json
      description: Retrieves the user's information using the access token stored
        in cookies.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_domain.User'
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Get User Information
      tags:
      - User
  /api/v1/users/get/logout:
    get:
      consumes:
      - application/json
      description: Logout the current user
      produces:
      - application/json
      responses:
        "200":
          description: 'status: success'
        "400":
          description: 'status: fail, message: detailed error message'
        "401":
          description: 'status: fail, message: You are not login!'
      summary: Logout user
      tags:
      - User
  /api/v1/users/get/refresh:
    get:
      consumes:
      - application/json
      description: Refresh the user's access token using a valid refresh token stored
        in cookies.
      produces:
      - application/json
      responses:
        "200":
          description: 'status: success'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "403":
          description: 'status: fail, message: could not refresh access token'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Refresh Access Token
      tags:
      - User
  /api/v1/users/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: User data
        in: body
        name: LoginUserRequestDto
        required: true
        schema:
          $ref: '#/definitions/user_domain.SignIn'
      produces:
      - application/json
      responses:
        "201":
          description: 'status: success'
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Login user
      tags:
      - User
  /api/v1/users/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - multipart/form-data
      description: Register a new user with form data
      parameters:
      - description: Email of the user
        example: '"john.doe@example.com"'
        in: formData
        name: email
        required: true
        type: string
      - description: Password of the user
        example: '"securepassword123"'
        in: formData
        name: password
        required: true
        type: string
      - description: Full name of the user
        example: '"John Doe"'
        in: formData
        name: fullName
        required: true
        type: string
      - description: Avatar URL of the user
        example: '"http://example.com/avatar.jpg"'
        in: formData
        name: avatarUrl
        required: true
        type: string
      - description: Image file to upload
        in: formData
        name: file
        required: true
        type: file
      - description: Phone number of the user
        example: '"+1234567890"'
        in: formData
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: 'status: success'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'status: error'
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Register user
      tags:
      - User
  /api/v1/users/update:
    patch:
      consumes:
      - application/json
      description: Updates the user's first name, last name, and username
      produces:
      - application/json
      responses:
        "400":
          description: 'status: fail, message: detailed error message'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'status: fail, message: You are not logged in!'
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Update User Information
      tags:
      - User
swagger: "2.0"
